import { WorkspaceGuardRuntimeProviderConsumerRuntimeWorkspaceOrchestratorRegistry } from "./workspaceGuardRuntimeProviderConsumerRuntimeWorkspaceOrchestratorRegistry";

export class WorkspaceGuardRuntimeProviderConsumerRuntimeWorkspaceOrchestratorRegistryFactory {
  static create(): WorkspaceGuardRuntimeProviderConsumerRuntimeWorkspaceOrchestratorRegistry {
    return new WorkspaceGuardRuntimeProviderConsumerRuntimeWorkspaceOrchestratorRegistry();
  }
}